---
title: "EpiScore"
author: "Daniel Monyak"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    code_folding: "hide"
editor_options: 
  markdown: 
    wrap: 72
params:
  loadAvgData: False
  methylRDS: False
  dataset: 'Lund'
  # methyl_filename: 'TCGA.methyl.rds'
  methyl_filename: "GSE75067_betaValues.txt"
---

```{r, warning=F, message=F}
## Load packages and import data

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(jsonlite)
library(EpiSCORE)
library(kableExtra)
data(BreastRef)

consts <- read_json(file.path(repo_dir, 'src', 'consts.json'))
source(file.path(repo_dir, 'src', 'EpiClockUtil.R'))

proj_dir <- file.path(consts[['official_indir']], params$dataset)
avgMethylFilename <- sprintf('%s.avBRCA.m.rds', params$dataset)

if (params$loadAvgData) {
  avBRCA.m <- readRDS(file.path(proj_dir, avgMethylFilename))
} else {
  if (params$methylRDS) {
    dataBRCA.m <- readRDS(file.path(proj_dir, params$methyl_filename))
  } else {
    dataBRCA.m <- processBetaValues(
      file.path(proj_dir, params$methyl_filename)
      )
  }
  
  # Construct a DNAm matrix at gene-promoter level
  avBRCA.m <- constAvBetaTSS(dataBRCA.m, type="450k")
  saveRDS(avBRCA.m, file.path(proj_dir, avgMethylFilename))
}
```


```{r, warning=F, message=F}
# Estimation of cell-type fractions using a DNAm reference matrix
estF.o <- wRPC(avBRCA.m,
               ref=mrefBreast.m,
               useW=TRUE, wth=0.4, maxit=200 # Parameters used in tutorial vignette
               )
celltype.fractions <- estF.o$estF
rownames(celltype.fractions) <- getTumorIDs(rownames(celltype.fractions))

saveRDS(celltype.fractions,
        file.path(proj_dir, 'EpiSCORE.celltype.fractions.rds'))
```

## First 6 rows of output

```{r}
head(celltype.fractions) |> kable()
```

```{r, warning=F, message=F}

clinical <- read.table(file.path(
  consts['TCGA_datadir'],
  'TCGA.clinical.annotated_revision.tsv'), sep='\t',
  header=T)

# No tumors are duplicated
# print(any(duplicated(rownames(celltype.fractions))))
# [1] FALSE

celltype.fractions <- merge(celltype.fractions,
                            clinical[, c('Sample.ID', 'CPE', 'c_beta')],
                            by.x=0, by.y='Sample.ID', all.x=T)
celltype.fractions$Epithelial <- celltype.fractions$Basal + celltype.fractions$Luminal
```

## Summary table of epithelial

Epithelial = Luminal + Basal
```{r}
format(as.data.frame(t(as.matrix(summary(celltype.fractions$Epithelial)))), digits=2) |>
  kable()
```

## Epithelial vs. CPE as a purity measure
```{r}
celltype.fractions %>%
  ggplot(aes(x=CPE, y=Epithelial)) +
  geom_point(color='darkred', size=1) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "black") +
  theme_classic() + 
  xlim(0, 1) + ylim(0, 1)

summary(lm(Epithelial ~ CPE, data=celltype.fractions))

R.value <- round(cor(celltype.fractions$Epithelial, celltype.fractions$CPE), 2)
```


Correlation of epithelial fraction with CPE: R = `r R.value`